### ISSUE TITLE
how to setup this script

### ISSUE THREAD

**Issue by zssoundguy123** [zapier/sentinel-graylog#2]
Hello,
Can you help me, how to install and use this script?

Cheers,
Zsolt

**Comment by bryanhelmig** [comment]
Just run the script according to the readme https://github.com/zapier/sentinel-graylog/blob/master/README.md. There really isn't that much more to it. :-)

**Comment by zssoundguy123** [comment]
When I start it, it says: 
`WARNING: Your kernel does not support memory swappiness capabilities, memory swappiness discarded.`
In the other console where I started `docker -d` it says:
`WARN[0015] Your kernel does not support memory swappiness capabilities, memory swappiness discarded.
WARN[0015] Your kernel does not support OOM notifications: There is no path for "memory" in state`
