### ISSUE TITLE
memory swappiness capabilities

### ISSUE THREAD

**Issue by zssoundguy123** [zapier/sentinel-graylog#3]
Hello!
When I start it, it says: 
WARNING: Your kernel does not support memory swappiness capabilities, memory swappiness discarded.
In the other console where I started docker -d it says:
WARN[0015] Your kernel does not support memory swappiness capabilities, memory swappiness discarded. WARN[0015] Your kernel does not support OOM notifications: There is no path for "memory" in state

What can I do?

Cheers, 
Zsolt

**Comment by robgolding** [comment]
Hey Zsolt,

This is an issue with Docker: https://github.com/docker/docker/issues/16298

That said, it looks like you can safely ignore the warnings!
